# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Map_Factory' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Map_Factory

  target 'Map_FactoryTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Map_FactoryUITests' do
    inherit! :search_paths
    # Pods for testing
  end
pod 'BaiduMapKit'
pod 'AMap3DMap'
pod 'GoogleMaps', '~> 2.2.0'
end
